
var $=function(sElem){return document.getElementById(sElem);};if(!BLUEBOY){var BLUEBOY={};}
BLUEBOY.utility={addLoadEvent:function(func){var oldOnload=window.onload;if(typeof window.onload!='function')
window.onload=func;else{window.onload=function(){oldOnload();func();}}},blur:function(aTemp){var aTemp=aTemp||[];var cElems=aTemp[1]?BLUEBOY.utility.normalizeElement(aTemp[1]).getElementsByTagName(aTemp[0]||"a"):document.getElementsByTagName(aTemp[0]||"a");var iElemsLength=cElems.length;for(var i=0;i<iElemsLength;i++){if(cElems[i].type!="text"){cElems[i].onfocus=function(){if(this.blur)this.blur();};}}
if(arguments.length>1){for(var i=0;arguments[i]!=null;i++){arguments.callee(arguments[i]);}}},cleanWhitespace:function(vElem){var oRoot=vElem?BLUEBOY.utility.normalizeElement(vElem):document;for(var i=0;i<oRoot.childNodes.length;i++){var oChildNode=oRoot.childNodes[i];if(oChildNode.nodeType==3&&!/\S/.test(oChildNode.nodeValue)){oRoot.removeChild(oRoot.childNodes[i]);i--;}
if(oChildNode.nodeType==1){arguments.callee(oChildNode);}}
if(arguments.length>1){for(var i=1;arguments[i]!=null;i++){arguments.callee(arguments[i]);}}},counter:(function(){var i=0;return function(){return i++;};})(),createElem:function(oTemp){var oElem=document.createElement(oTemp.elem);if(oTemp.attributes){for(var i in oTemp.attributes){oElem[i]=oTemp.attributes[i];}}
if(oTemp.style){for(var i in oTemp.style){oElem.style[i]=oTemp.style[i];}}
if(oTemp.children){var iChildrenLength=oTemp.children.length;for(var i=0;i<iChildrenLength;i++){oElem.appendChild(oTemp.children[i]);}}
if(oTemp.parent&&oTemp.inDOM===false){var oParent=this.normalizeElement(oTemp.parent);oParent=appendChild(oElem);return oParent;}else if(oTemp.parent){var oParent=this.normalizeElement(oTemp.parent);oParent.appendChild(oElem);}else{return oElem;}},getElementsByClassName:function(sClassname,vRootElem,sSearchBy){if(!sClassname)return false;var aTemp=[];var reTemp=new RegExp("\\b"+sClassname+"\\b");if(vRootElem){var cElems=this.normalizeElement(vRootElem).getElementsByTagName(sSearchBy);}else{var cElems=document.getElementsByTagName("*")||document.all;}
var cElemsLength=cElems.length;for(var i=0,j=cElemsLength;i<j;i++){if(reTemp.test(cElems[i].className)){aTemp.push(cElems[i]);}}
return aTemp;},getStyle:function(oElem,sName){if(oElem.style[sName])return oElem.style[sName];else if(oElem.currentStyle)return oElem.currentStyle[sName];else if(document.defaultView&&document.defaultView.getComputedStyle){sName=sName.replace(/([A-Z])/g,"-$1");sName=sName.toLowerCase();var sTemp=document.defaultView.getComputedStyle(oElem,"");return sTemp&&sTemp.getPropertyValue(sName);}else return null;},insertAfter:function(oNewElement,oTargetElement){var oParent=oTargetElement.parentNode;if(oParent.lastChild==oTargetElement){oParent.appendChild(oNewElement);}else{oParent.insertBefore(oNewElement,oTargetElement.nextSibling);}},invoker:function(vElem){var aNamespace=[];if(vElem.constructor===Array){var iElemLength=vElem.length;for(var i=0;i<iElemLength;i++){aNamespace=vElem[i].split(".");BLUEBOY[aNamespace[0]][aNamespace[1]]();}}else{aNamespace=vElem.split(".");BLUEBOY[aNamespace[0]][aNamespace[1]]();}},normalizeElement:function(vElem){return vElem.constructor===String?$(vElem):vElem;},targetBlank:function(vParent){var cLinks=vParent?this.normalizeElement(vParent).getElementsByTagName("a"):document.getElementsByTagName("a");var iLinksLength=cLinks.length;for(var i=0;i<iLinksLength;i++){cLinks[i].onclick=function(){var oChild=window.open(this.getAttribute("href"));return!oChild?true:false;};}}};